source:
  build_context:
    url: https://github.com/mihaTrajbaric/generic_docker_build_context.git
  dockerfile:
    url: https://raw.githubusercontent.com/mihaTrajbaric/image-builder-test-files/master/python_build_context/Dockerfile
target:
  images:
  - image: repository/build-context
    tag: latest
  registry:
    password: password
    url: docker.io
    username: user
