source:
  build_context:
    url: https://github.com/mihaTrajbaric/generic_docker_build_context.git
  dockerfile:
    url: https://raw.githubusercontent.com/mihaTrajbaric/image-builder-test-files/master/python_build_context/Dockerfile
target:
  images:
  - image: tests/build-context
    tag: latest
  registry_ip: localhost:5000
