apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-builder-api
#  annotations:
#    container.apparmor.security.beta.kubernetes.io/img: unconfined
#    container.seccomp.security.alpha.kubernetes.io/img: unconfined
  labels:
    app: image-builder
spec:
  replicas: 5
  selector:
    matchLabels:
      app: image-builder
  template:
    metadata:
      labels:
        app: image-builder
    spec:
      containers:
      - name: image-builder
        image: sodaliteh2020/image-builder-api:k8s
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        env:
          - name: AUTH_API_KEY
            value: test
          - name: DEBUG
            value: "true"
          - name: LOG_LEVEL
            value: debug
#        securityContext:
#          procMount: Unmasked

---
apiVersion: v1
kind: Service
metadata:
  name: image-builder-api
spec:
  selector:
    app: image-builder
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  type: NodePort

