version: '3.7'
services:

  api:
    image: image-builder-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AUTH_API_KEY: test
      DEBUG: "true"
      LOG_LEVEL: debug
      REGISTRY_IP: [ registry ip here ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.docker:/root/.docker"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=web"

  proxy:
    image: library/traefik:v2.3.4
    command:
      - "--accesslog=true"
      - "--log.level=info"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      # don't use the following in production scenarios!
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.traefik.address=:8081"
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      # don't use this in production scenarios!
      - "127.0.0.1:8081:8081"