version: '3.7'
services:

  api:
    image: image-builder-api
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      AUTH_API_KEY: test
      DEBUG: "true"
      LOG_LEVEL: debug
      IMAGEBUILDER_DATABASE_IP: postgres
      IMAGEBUILDER_DATABASE_NAME: postgres
      IMAGEBUILDER_DATABASE_USER: postgres
      IMAGEBUILDER_DATABASE_PASSWORD: password
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=web"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
#    volumes:
#      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"

  proxy:
    image: library/traefik:v2.3.4
    command:
      - "--accesslog=true"
      - "--log.level=info"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      # don't use the following in production scenarios!
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.traefik.address=:8081"
    depends_on:
      - api
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      # don't use this in production scenarios!
      - "127.0.0.1:8081:8081"