# docker-compose.yml

version: '3'
services:

  flask:
    image: image-builder-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/image-builder"
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx:
    image: image-builder-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
      - 443:443
    depends_on:
      - flask
    volumes:
      - "/etc/ssl/certs:/etc/nginx/certs"