# Dockerfile-flask

#####################################################
#################     START BIG     #################
#####################################################

FROM python:3.6-alpine as big

# Install prerequisites
RUN apk add build-base libffi-dev postgresql-dev bash

# install python packages
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip wheel --wheel-dir=/root/wheels -r requirements.txt

#####################################################
#################   MAKE IT SMALL   #################
#####################################################

FROM python:3.6-alpine as small

# Install prerequisites
RUN apk add build-base libffi-dev postgresql-dev bash

# copy python packages from big image
COPY requirements.txt .
COPY --from=big /root/wheels /root/wheels
RUN pip install --find-links=/root/wheels -r requirements.txt

ENV APP /image-builder
RUN mkdir $APP
WORKDIR $APP

# We copy codebase into the image
COPY . .

# Expose the port uWSGI will listen on
EXPOSE 5000


CMD [ "uwsgi", "--ini", "app.ini" ]