source:
  build_context:
    password: my_password_or_token
    url: https://url/to/git/repo/with/build_context.git
    username: my_username
  password: my_optional_password
  type: dockerfile
  url: https://link/to/Dockerfile
  username: my_optional_username
target:
  image_name: my_image_name
  image_tag: my_image_tag
  registry_ip: localhost:5000
