apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB: postgres
  USER: postgres
  PASSWORD: postgres

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-url
data:
  db_ip: postgres-service