apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-builder-api
  annotations:
    container.apparmor.security.beta.kubernetes.io/image-builder: unconfined
    container.seccomp.security.alpha.kubernetes.io/image-builder: unconfined
  labels:
    app: image-builder
spec:
  replicas: 5
  selector:
    matchLabels:
      app: image-builder
  template:
    metadata:
      labels:
        app: image-builder
    spec:
      containers:
      - name: image-builder
        image: sodaliteh2020/image-builder-api:k8s3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        env:
          # ---- remove in production ---
          - name: AUTH_API_KEY
            value: test
          # ---- end remove in production ---

          # --- fill with keycloak values ---
          - name: OIDC_INTROSPECTION_ENDPOINT
            value: http://oicd-enpoindt.com
          - name: OIDC_CLIENT_ID
            value: fixmeClientId
          - name: OIDC_CLIENT_SECRET
            value: fixmeClientSecret
          # --- end fill with keycloak values ---

          - name: LOG_LEVEL
            value: debug
          - name: IMAGEBUILDER_DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-url
                key: db_ip
        envFrom:
          - prefix: IMAGEBUILDER_DATABASE_
            secretRef:
              name: postgres-secret
        securityContext:
          procMount: Unmasked

---
apiVersion: v1
kind: Service
metadata:
  name: image-builder-api
spec:
  selector:
    app: image-builder
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  type: NodePort
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1

